//
//  ViewController.swift
//  CaptureVideo
//
//  Created by melisa öztürk on 9.05.2020.
//  Copyright © 2020 melisa öztürk. All rights reserved.
//

import UIKit
import Photos

class ViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    //Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    let assetWriterController = AssetWriterController()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        configureCameraController()
        styleCaptureButton()
//        assetWriterController.setup()
    }
    
    override var prefersStatusBarHidden: Bool {
        return true
    }
    
    @IBAction func toggleFlash(_ sender: UIButton) {
    }
    
    @IBAction func switchCameras(_ sender: UIButton) {
        do {
            try assetWriterController.switchCameras()
        }

        catch {
            print(error)
        }
    }
    
    @IBAction func captureImage(_ sender: UIButton) {
//        TODO: StartRecording

        assetWriterController.startRecording(view: self.capturePreviewView)

    }
    
    
    @IBAction func btnStop(_ sender: Any) {
        assetWriterController.stopRecording()
    }
    
    //     prepares our camera controller like we designed it to
    func configureCameraController() {
        assetWriterController.prepare {(error) in
            if let error = error {
                print(error)
            }
        }
        self.assetWriterController.displayPreview(on: self.capturePreviewView)
    }
    
    private func styleCaptureButton() {
        captureButton.layer.borderColor = UIColor.black.cgColor
        captureButton.layer.borderWidth = 2

        captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
    }
    
}
