//
//  ViewController.swift
//  CaptureVideo
//
//  Created by melisa öztürk on 9.05.2020.
//  Copyright © 2020 melisa öztürk. All rights reserved.
//

import UIKit
import Photos

class ViewController: UIViewController {
    
    @IBOutlet fileprivate var captureButton: UIButton!
    //Displays a preview of the video output generated by the device's cameras.
    @IBOutlet fileprivate var capturePreviewView: UIView!
    
    let streamController = StreamController()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        styleCaptureButton()
    }
    
    override var prefersStatusBarHidden: Bool {
        return true
    }
    
    @IBAction func toggleFlash(_ sender: UIButton) {
    }
    
    @IBAction func switchCameras(_ sender: UIButton) {
        do {
            try streamController.switchCameras()
        }
     
        catch {
            print(error)
        }
    }
    
    @IBAction func captureImage(_ sender: UIButton) {
//        TODO: StartRecording
//        streamController.captureVideo {(output, error) in
//            guard let output = output else {
//                print(error ?? "Video capture error")
//                return
//            }
//            #if DEBUG
//            print("RECORDING ..")
//            #endif
//            try? PHPhotoLibrary.shared().performChangesAndWait {
//                PHAssetChangeRequest.creationRequestForAssetFromVideo(atFileURL: output as CGPath)
//            }
//        }
        configureCameraController()

    }
    
    
    @IBAction func btnStop(_ sender: Any) {
        streamController.stopRecording()
    }
    
    //     prepares our camera controller like we designed it to
    func configureCameraController() {
        streamController.prepare {(error) in
            if let error = error {
                print(error)
            }
            
            try? self.streamController.displayPreview(on: self.capturePreviewView)
        }
    }
    
    func styleCaptureButton() {
        captureButton.layer.borderColor = UIColor.black.cgColor
        captureButton.layer.borderWidth = 2
        
        captureButton.layer.cornerRadius = min(captureButton.frame.width, captureButton.frame.height) / 2
    }
    
}
